apiVersion: v1
kind: Service
metadata:
  name: q-entities
spec:
  type: NodePort
  ports:
  - port: 80
  selector:
    app: q-entities
---
apiVersion: apps/v1 
kind: Deployment
metadata:
  name: q-entities
spec:
  selector:
    matchLabels:
      app: q-entities
  replicas: 1
  template:
    metadata:
      labels:
        app: q-entities
    spec:
      imagePullSecrets:
        - name: acrsecret
      containers:
      - name: q-entities
        image: q2ffhackaton.azurecr.io/q-entities:latest
        env:
        - name: AzureAd__ClientSecret
          value: ""
        - name: ASPNETCORE_URLS
          value: http://+:80
        - name: FLAGD_HOST
          value: "flagd"
        - name: FLAGD_PORT
          value: "8013"
        ports:
          - containerPort: 80
            protocol: TCP